export const actionTypes = {
  shoppingListActions: {
    FETCH_ITEM_LIST_STARTED: "FETCH_ITEM_LIST_STARTED",
    FETCH_ITEM_LIST_SUCCESS: "FETCH_ITEM_LIST_SUCCESS",
    FETCH_ITEM_LIST_FAILED: "FETCH_ITEM_LIST_FAILED"
  },
  cartActions: {
    FETCH_CART_ITEM_LIST_STARTED: "FETCH_CART_ITEM_LIST_STARTED",
    FETCH_CART_ITEM_LIST_SUCCESS: "FETCH_CART_ITEM_LIST_SUCCESS",
    FETCH_CART_ITEM_LIST_FAILED: "FETCH_CART_ITEM_LIST_FAILED",
    ADD_TO_CART: "ADD_TO_CART",
    INCREMENT_COUNT: "INCREMENT_COUNT",
    DECREMENT_COUNT: "DECREMENT_COUNT",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    CLEAR_CART: "CLEAR_CART",
    UPDATE_TOTAL_COST: "UPDATE_TOTAL_COST"
  }
};
